import { createFileRoute, Link } from "@tanstack/react-router";
import { Building2, HandHeart, Leaf, Recycle, Users, Utensils } from "lucide-react";
import { useEffect, useState } from "react";
import { StatCard } from "@/components/site/StatCard";
import { PageShell } from "@/components/site/PageShell";
import { Button } from "@/components/ui/button";
import { useStore } from "@/lib/foodbridge/store";

export const Route = createFileRoute("/impact")({
  head: () => ({
    meta: [
      { title: "FoodBridge Impact — Meals Rescued and Waste Avoided" },
      {
        name: "description",
        content:
          "Track the social and environmental impact of FoodBridge: meals rescued, people served, NGOs connected and food waste reduced.",
      },
      { property: "og:title", content: "FoodBridge Impact" },
      {
        property: "og:description",
        content: "Meals rescued, people served and kilograms of food waste avoided.",
      },
    ],
  }),
  component: Impact,
});

/** Lightweight count-up used by the impact counters (single rAF pass, no library). */
function useCountUp(target: number, duration = 900) {
  const [value, setValue] = useState(0);
  useEffect(() => {
    let raf = 0;
    const start = performance.now();
    const tick = (t: number) => {
      const p = Math.min(1, (t - start) / duration);
      setValue(Math.round(target * (1 - Math.pow(1 - p, 3))));
      if (p < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [target, duration]);
  return value;
}

function Counter({ value, label, suffix }: { value: number; label: string; suffix?: string }) {
  const n = useCountUp(value);
  return (
    <div className="rounded-2xl border border-primary-foreground/20 bg-primary-foreground/10 p-6 text-center">
      <p className="font-display text-3xl font-bold sm:text-4xl">
        {n.toLocaleString("en-IN")}
        {suffix}
      </p>
      <p className="mt-1 text-sm opacity-90">{label}</p>
    </div>
  );
}

function Impact() {
  const { impact } = useStore();

  return (
    <PageShell
      eyebrow="Impact"
      title="Every rescued meal counts"
      description="Social and environmental impact generated by the FoodBridge network."
      actions={
        <Button asChild>
          <Link to="/donate">Add to the impact</Link>
        </Button>
      }
    >
      <div className="brand-gradient grid gap-4 rounded-3xl p-6 text-primary-foreground sm:grid-cols-2 lg:grid-cols-4">
        <Counter value={impact.mealsRescued} label="Meals rescued" />
        <Counter value={impact.peopleServed} label="People served" />
        <Counter value={impact.wasteReducedKg} label="Kg food waste reduced" />
        <Counter value={impact.ngos} label="NGOs connected" />
      </div>

      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard icon={HandHeart} label="Total donations" value={impact.donations} />
        <StatCard icon={Utensils} label="Completed donations" value={impact.completed} />
        <StatCard icon={Building2} label="Active donations" value={impact.active} />
        <StatCard
          icon={Recycle}
          label="CO₂e avoided (est.)"
          value={`${Math.round(impact.wasteReducedKg * 2.5).toLocaleString("en-IN")} kg`}
        />
      </div>

      <section className="mt-12 grid gap-6 md:grid-cols-3">
        {[
          {
            title: "Environmental",
            body: "Diverting edible food from landfill avoids methane emissions and the water, land and energy embedded in producing that food.",
          },
          {
            title: "Social",
            body: "Verified NGOs and community kitchens receive predictable, fresh food supply so they can plan daily meal services with confidence.",
          },
          {
            title: "Economic",
            body: "Donors reduce waste-disposal costs and gain a transparent record of contribution for CSR and sustainability reporting.",
          },
        ].map((c) => (
          <article key={c.title} className="surface-card p-6">
            <span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary">
              <Leaf className="size-5" aria-hidden />
            </span>
            <h2 className="mt-4 font-display text-lg font-semibold">{c.title}</h2>
            <p className="mt-2 text-sm text-muted-foreground">{c.body}</p>
          </article>
        ))}
      </section>

      <div className="surface-card mt-12 flex flex-col items-center gap-4 p-10 text-center">
        <Users className="size-8 text-primary" aria-hidden />
        <h2 className="font-display text-2xl font-bold">Be part of the next 100,000 meals</h2>
        <div className="flex flex-wrap justify-center gap-3">
          <Button asChild>
            <Link to="/donate">Donate Food</Link>
          </Button>
          <Button asChild variant="outline">
            <Link to="/find-food">Register as NGO</Link>
          </Button>
        </div>
      </div>
    </PageShell>
  );
}
