import food1 from "@/assets/food-1.jpg";
import food2 from "@/assets/food-2.jpg";
import food3 from "@/assets/food-3.jpg";
import food4 from "@/assets/food-4.jpg";
import type {
  ActivityEvent,
  AppNotification,
  AppUser,
  Donation,
  FoodRequest,
  Ngo,
} from "./types";

/** City centre used as the default "current location" for the demo. */
export const CITY_CENTER = { lat: 18.5204, lng: 73.8567, label: "Pune, Maharashtra" };

export const FOOD_IMAGES = [food1, food2, food3, food4];

const now = Date.now();
const iso = (minutesFromNow: number) => new Date(now + minutesFromNow * 60000).toISOString();

export const DEMO_USERS: AppUser[] = [
  {
    id: "USR-DONOR-01",
    name: "Aarav Mehta",
    email: "donor@foodbridge.app",
    phone: "+91 98200 11223",
    role: "donor",
    organization: "Spice Garden Restaurant",
    location: "Kalyani Nagar, Pune",
    lat: 18.5486,
    lng: 73.9034,
    createdAt: iso(-60 * 24 * 40),
  },
  {
    id: "USR-NGO-01",
    name: "Priya Nair",
    email: "ngo@foodbridge.app",
    phone: "+91 98111 44556",
    role: "ngo",
    organization: "Hope Foundation",
    location: "Koregaon Park, Pune",
    lat: 18.5362,
    lng: 73.8939,
    verified: true,
    createdAt: iso(-60 * 24 * 90),
  },
  {
    id: "USR-ADMIN-01",
    name: "FoodBridge Admin",
    email: "admin@foodbridge.app",
    phone: "+91 90000 00000",
    role: "admin",
    organization: "FoodBridge",
    location: "Shivajinagar, Pune",
    lat: 18.5308,
    lng: 73.8475,
    verified: true,
    createdAt: iso(-60 * 24 * 200),
  },
];

export const DEMO_NGOS: Ngo[] = [
  {
    id: "NGO-001",
    name: "Hope Foundation",
    contactPerson: "Priya Nair",
    phone: "+91 98111 44556",
    location: "Koregaon Park, Pune",
    lat: 18.5362,
    lng: 73.8939,
    capacity: 120,
    urgency: "high",
    foodType: "Any",
    verified: true,
    type: "NGO",
  },
  {
    id: "NGO-002",
    name: "Care Community",
    contactPerson: "Rahul Deshmukh",
    phone: "+91 98222 77881",
    location: "Viman Nagar, Pune",
    lat: 18.567,
    lng: 73.9143,
    capacity: 80,
    urgency: "medium",
    foodType: "Vegetarian",
    verified: true,
    type: "Community Kitchen",
  },
  {
    id: "NGO-003",
    name: "Food Support Center",
    contactPerson: "Sana Shaikh",
    phone: "+91 97555 22110",
    location: "Deccan Gymkhana, Pune",
    lat: 18.5167,
    lng: 73.8412,
    capacity: 200,
    urgency: "critical",
    foodType: "Any",
    verified: true,
    type: "Food Bank",
  },
  {
    id: "NGO-004",
    name: "Hunger Relief NGO",
    contactPerson: "Imran Qureshi",
    phone: "+91 96333 88220",
    location: "Hadapsar, Pune",
    lat: 18.5089,
    lng: 73.926,
    capacity: 60,
    urgency: "low",
    foodType: "Vegetarian",
    verified: false,
    type: "NGO",
  },
];

export const DEMO_DONATIONS: Donation[] = [
  {
    donationId: "FB-2481",
    donorId: "USR-DONOR-01",
    donorName: "Aarav Mehta",
    organization: "Spice Garden Restaurant",
    donorType: "Restaurant",
    phone: "+91 98200 11223",
    email: "donor@foodbridge.app",
    foodType: "Veg Thali (rice, dal, sabzi, roti)",
    category: "Cooked Meals",
    diet: "Vegetarian",
    quantity: "12 trays",
    servings: 120,
    preparedAt: iso(-75),
    expiryTime: iso(180),
    address: "Spice Garden, Kalyani Nagar, Pune",
    lat: 18.5486,
    lng: 73.9034,
    availableTime: "Now – 9:30 PM",
    description: "Surplus from a corporate lunch order. Packed and sealed in food-grade trays.",
    image: food1,
    status: "available",
    createdAt: iso(-25),
  },
  {
    donationId: "FB-2477",
    donorId: "USR-DONOR-02",
    donorName: "Meera Joshi",
    organization: "Sinhgad College Canteen",
    donorType: "Canteen",
    phone: "+91 99887 66554",
    email: "canteen@sinhgad.demo",
    foodType: "Rice, Dal & Mixed Vegetables",
    category: "Cooked Meals",
    diet: "Vegetarian",
    quantity: "5 containers",
    servings: 50,
    preparedAt: iso(-100),
    expiryTime: iso(120),
    address: "Sinhgad Road, Pune",
    lat: 18.4655,
    lng: 73.8259,
    availableTime: "Now – 8:00 PM",
    description: "Unserved canteen food from today's lunch counter.",
    image: food2,
    status: "matched",
    matchedNgoId: "NGO-003",
    matchScore: 88,
    createdAt: iso(-70),
  },
  {
    donationId: "FB-2470",
    donorId: "USR-DONOR-03",
    donorName: "Nikhil Rao",
    organization: "Grand Orchid Event Hall",
    donorType: "Event Hall",
    phone: "+91 90909 12121",
    email: "events@grandorchid.demo",
    foodType: "Buffet Mixed Menu",
    category: "Buffet Surplus",
    diet: "Mixed",
    quantity: "8 chafing trays",
    servings: 80,
    preparedAt: iso(-140),
    expiryTime: iso(90),
    address: "Baner Road, Pune",
    lat: 18.5593,
    lng: 73.7868,
    availableTime: "Now – 7:30 PM",
    description: "Wedding reception surplus. Includes veg and non-veg, packed separately.",
    image: food3,
    status: "accepted",
    matchedNgoId: "NGO-001",
    matchScore: 92,
    createdAt: iso(-120),
  },
  {
    donationId: "FB-2465",
    donorId: "USR-DONOR-04",
    donorName: "Shalini Kulkarni",
    organization: "Household Donation",
    donorType: "Household",
    phone: "+91 93434 55667",
    email: "shalini@demo.app",
    foodType: "Packed Food Packets (poha, upma)",
    category: "Packed Food",
    diet: "Vegetarian",
    quantity: "30 packets",
    servings: 30,
    preparedAt: iso(-200),
    expiryTime: iso(240),
    address: "Aundh, Pune",
    lat: 18.5606,
    lng: 73.8077,
    availableTime: "Now – 10:00 PM",
    description: "Freshly packed breakfast packets from a family function.",
    image: food4,
    status: "pickup",
    matchedNgoId: "NGO-002",
    matchScore: 84,
    createdAt: iso(-180),
  },
  {
    donationId: "FB-2452",
    donorId: "USR-DONOR-01",
    donorName: "Aarav Mehta",
    organization: "Spice Garden Restaurant",
    donorType: "Restaurant",
    phone: "+91 98200 11223",
    email: "donor@foodbridge.app",
    foodType: "Paneer Curry & Jeera Rice",
    category: "Cooked Meals",
    diet: "Vegetarian",
    quantity: "6 trays",
    servings: 60,
    preparedAt: iso(-60 * 26),
    expiryTime: iso(-60 * 20),
    address: "Spice Garden, Kalyani Nagar, Pune",
    lat: 18.5486,
    lng: 73.9034,
    availableTime: "Yesterday 6:00 PM – 9:00 PM",
    description: "Completed pickup — distributed to 60 people.",
    image: food1,
    status: "completed",
    matchedNgoId: "NGO-001",
    matchScore: 95,
    createdAt: iso(-60 * 27),
  },
  {
    donationId: "FB-2440",
    donorId: "USR-DONOR-05",
    donorName: "Hotel Riverview",
    organization: "Hotel Riverview",
    donorType: "Hotel",
    phone: "+91 91234 09876",
    email: "fnb@riverview.demo",
    foodType: "Breakfast Buffet Surplus",
    category: "Buffet Surplus",
    diet: "Mixed",
    quantity: "4 trays",
    servings: 40,
    preparedAt: iso(-60 * 50),
    expiryTime: iso(-60 * 46),
    address: "Bund Garden Road, Pune",
    lat: 18.5362,
    lng: 73.8791,
    availableTime: "Cancelled",
    description: "Cancelled by donor — food consumed on site.",
    image: food3,
    status: "cancelled",
    createdAt: iso(-60 * 52),
  },
];

export const DEMO_REQUESTS: FoodRequest[] = [
  {
    requestId: "REQ-1180",
    ngoId: "NGO-003",
    organization: "Food Support Center",
    contactPerson: "Sana Shaikh",
    phone: "+91 97555 22110",
    location: "Deccan Gymkhana, Pune",
    lat: 18.5167,
    lng: 73.8412,
    foodType: "Any",
    requiredServings: 200,
    people: 200,
    urgency: "critical",
    requiredBy: "Today, 8:00 PM",
    createdAt: iso(-45),
    status: "open",
  },
  {
    requestId: "REQ-1176",
    ngoId: "NGO-002",
    organization: "Care Community",
    contactPerson: "Rahul Deshmukh",
    phone: "+91 98222 77881",
    location: "Viman Nagar, Pune",
    lat: 18.567,
    lng: 73.9143,
    foodType: "Vegetarian",
    requiredServings: 80,
    people: 80,
    urgency: "medium",
    requiredBy: "Today, 9:00 PM",
    createdAt: iso(-160),
    status: "open",
  },
];

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: "NTF-01",
    title: "New donation available nearby",
    message: "Spice Garden Restaurant posted 120 vegetarian meals · 2.1 km away.",
    kind: "donation",
    audience: "ngo",
    createdAt: iso(-25),
    read: false,
  },
  {
    id: "NTF-02",
    title: "Donation accepted",
    message: "Hope Foundation accepted donation FB-2470 (80 meals).",
    kind: "match",
    audience: "donor",
    createdAt: iso(-110),
    read: false,
  },
  {
    id: "NTF-03",
    title: "Pickup reminder",
    message: "Pickup for FB-2465 starts in 20 minutes at Aundh, Pune.",
    kind: "pickup",
    audience: "all",
    createdAt: iso(-15),
    read: true,
  },
];

export const DEMO_ACTIVITY: ActivityEvent[] = [
  {
    id: "ACT-01",
    label: "Donation posted",
    detail: "Spice Garden Restaurant · 120 meals · Kalyani Nagar",
    kind: "posted",
    createdAt: iso(-25),
  },
  {
    id: "ACT-02",
    label: "NGO accepted",
    detail: "Hope Foundation accepted FB-2470 · 80 meals",
    kind: "accepted",
    createdAt: iso(-110),
  },
  {
    id: "ACT-03",
    label: "Pickup started",
    detail: "Care Community en route for FB-2465 · Aundh",
    kind: "pickup",
    createdAt: iso(-40),
  },
  {
    id: "ACT-04",
    label: "Donation completed",
    detail: "FB-2452 · 60 meals distributed by Hope Foundation",
    kind: "completed",
    createdAt: iso(-60 * 20),
  },
];

/** Base numbers so impact counters look realistic during the demo. */
export const BASE_IMPACT = {
  donations: 1284,
  mealsRescued: 96450,
  ngos: 142,
  peopleServed: 74320,
  wasteReducedKg: 28935,
};

export const DONATIONS_BY_DAY = [
  { day: "Mon", donations: 34, meals: 2100 },
  { day: "Tue", donations: 41, meals: 2680 },
  { day: "Wed", donations: 38, meals: 2450 },
  { day: "Thu", donations: 52, meals: 3320 },
  { day: "Fri", donations: 61, meals: 4110 },
  { day: "Sat", donations: 74, meals: 5240 },
  { day: "Sun", donations: 58, meals: 3980 },
];
